import type { DashboardData } from "@/lib/types";

export const dashboardMockData: DashboardData = {
  userId: "user-1",
  wallets: [
    {
      id: "wallet-1",
      userId: "user-1",
      name: "Carteira principal",
      balance: 150,
      currency: "BRL",
    },
  ],
  transactions: [
    {
      id: "transaction-1",
      userId: "user-1",
      walletId: "wallet-1",
      type: "entrada",
      status: "efetivada",
      description: "Compra de roupas",
      date: "2026-05-21",
      value: 100,
    },
    {
      id: "transaction-3",
      userId: "user-1",
      walletId: "wallet-1",
      type: "entrada",
      status: "efetivada",
      description: "Compra de roupas",
      date: "2026-05-21",
      value: 100,
    },
    {
      id: "transaction-4",
      userId: "user-1",
      walletId: "wallet-1",
      type: "entrada",
      status: "efetivada",
      description: "Compra de roupas",
      date: "2026-05-21",
      value: 100,
    },
    {
      id: "transaction-2",
      userId: "user-1",
      walletId: "wallet-1",
      type: "saida",
      status: "efetivada",
      description: "Compra de alimentos",
      date: "2026-05-21",
      value: 50,
    },
    {
      id: "transaction-5",
      userId: "user-1",
      walletId: "wallet-1",
      type: "saida",
      status: "efetivada",
      description: "Compra de alimentos",
      date: "2026-05-21",
      value: 50,
    },
    {
      id: "transaction-6",
      userId: "user-1",
      walletId: "wallet-1",
      type: "saida",
      status: "efetivada",
      description: "Compra de alimentos",
      date: "2026-05-20",
      value: 50,
    },
  ],
  creditCards: [],
};
